name: Auto Merge

on:
  workflow_run:
    workflows:
      - "Auto Approve Use Cases"
    types:
      - "completed"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" # add user access token in secrets to trigger workflows in master after merge
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
    